[build]
  command = "next build"
  publish = ".next"

[build.environment]
  NEXT_STATIC_DIRECTORY = "true"
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200